[project]
name = "cybersync"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.127.0",
    "uvicorn[standard]>=0.40.0",
]
